// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2QfTqmWqkYEYyxpgI0tMSpY5a7f9CgZM',
    appId: '1:861806536990:web:e48dc7c6602c1482e6410f',
    messagingSenderId: '861806536990',
    projectId: 'riverpod-course-vandad',
    authDomain: 'riverpod-course-vandad.firebaseapp.com',
    storageBucket: 'riverpod-course-vandad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBu-x8O7v9iXHB2ynNwHvTz-Ay5TDJUxk',
    appId: '1:861806536990:android:ce76f23e8f7bfb8fe6410f',
    messagingSenderId: '861806536990',
    projectId: 'riverpod-course-vandad',
    storageBucket: 'riverpod-course-vandad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADXK6bAAi9sXdynN1dTQD___XdSY9MmGA',
    appId: '1:861806536990:ios:46b369a5ce969b8be6410f',
    messagingSenderId: '861806536990',
    projectId: 'riverpod-course-vandad',
    storageBucket: 'riverpod-course-vandad.appspot.com',
    iosBundleId: 'com.mortadha.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADXK6bAAi9sXdynN1dTQD___XdSY9MmGA',
    appId: '1:861806536990:ios:7e01bf2c4f10c1cee6410f',
    messagingSenderId: '861806536990',
    projectId: 'riverpod-course-vandad',
    storageBucket: 'riverpod-course-vandad.appspot.com',
    iosBundleId: 'com.mortadha.instagramClone.RunnerTests',
  );
}
